"""Initial PostgreSQL schema

Revision ID: d7c00f5e9ed7
Revises: 
Create Date: 2026-10-01 13:56:06.428844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c00f5e9ed7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mobile_number', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('accommodation_type', sa.String(length=50), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_dept_year', 'students', ['department', 'academic_year'], unique=False)
    op.create_index(op.f('ix_students_academic_year'), 'students', ['academic_year'], unique=False)
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.create_index(op.f('ix_students_register_number'), 'students', ['register_number'], unique=True)
    op.create_table('placement_drives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('drive_name', sa.String(length=200), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('job_role', sa.String(length=150), nullable=True),
    sa.Column('ctc_lpa', sa.Float(), nullable=True),
    sa.Column('drive_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'drive_name', 'academic_year', name='uq_drive_company_name_year')
    )
    op.create_index(op.f('ix_placement_drives_academic_year'), 'placement_drives', ['academic_year'], unique=False)
    op.create_index(op.f('ix_placement_drives_company_id'), 'placement_drives', ['company_id'], unique=False)
    op.create_table('placement_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('stage_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'stage_order', name='uq_stage_drive_order')
    )
    op.create_index(op.f('ix_placement_stages_drive_id'), 'placement_stages', ['drive_id'], unique=False)
    op.create_table('student_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'student_id', name='uq_student_drive_reg')
    )
    op.create_index(op.f('ix_student_registrations_drive_id'), 'student_registrations', ['drive_id'], unique=False)
    op.create_index(op.f('ix_student_registrations_student_id'), 'student_registrations', ['student_id'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('drive_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('imported_by', sa.String(length=150), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['placement_stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_company_id'), 'import_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_import_logs_drive_id'), 'import_logs', ['drive_id'], unique=False)
    op.create_index(op.f('ix_import_logs_stage_id'), 'import_logs', ['stage_id'], unique=False)
    op.create_table('placements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('package_ctc', sa.Float(), nullable=True),
    sa.Column('offer_letter_url', sa.String(length=500), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['student_registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['placement_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'student_id', name='uq_placement_drive_student')
    )
    op.create_index(op.f('ix_placements_drive_id'), 'placements', ['drive_id'], unique=False)
    op.create_index(op.f('ix_placements_registration_id'), 'placements', ['registration_id'], unique=False)
    op.create_index(op.f('ix_placements_stage_id'), 'placements', ['stage_id'], unique=False)
    op.create_index(op.f('ix_placements_student_id'), 'placements', ['student_id'], unique=False)
    op.create_table('student_stage_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['student_registrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['placement_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'student_id', name='uq_stage_student_result')
    )
    op.create_index(op.f('ix_student_stage_results_registration_id'), 'student_stage_results', ['registration_id'], unique=False)
    op.create_index(op.f('ix_student_stage_results_stage_id'), 'student_stage_results', ['stage_id'], unique=False)
    op.create_index(op.f('ix_student_stage_results_student_id'), 'student_stage_results', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_stage_results_student_id'), table_name='student_stage_results')
    op.drop_index(op.f('ix_student_stage_results_stage_id'), table_name='student_stage_results')
    op.drop_index(op.f('ix_student_stage_results_registration_id'), table_name='student_stage_results')
    op.drop_table('student_stage_results')
    op.drop_index(op.f('ix_placements_student_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_stage_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_registration_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_drive_id'), table_name='placements')
    op.drop_table('placements')
    op.drop_index(op.f('ix_import_logs_stage_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_drive_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_company_id'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_student_registrations_student_id'), table_name='student_registrations')
    op.drop_index(op.f('ix_student_registrations_drive_id'), table_name='student_registrations')
    op.drop_table('student_registrations')
    op.drop_index(op.f('ix_placement_stages_drive_id'), table_name='placement_stages')
    op.drop_table('placement_stages')
    op.drop_index(op.f('ix_placement_drives_company_id'), table_name='placement_drives')
    op.drop_index(op.f('ix_placement_drives_academic_year'), table_name='placement_drives')
    op.drop_table('placement_drives')
    op.drop_index(op.f('ix_students_register_number'), table_name='students')
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.drop_index(op.f('ix_students_academic_year'), table_name='students')
    op.drop_index('idx_student_dept_year', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
